### ISSUE TITLE
发现一处 attrs 可能是 undefined 的情况

### ISSUE THREAD

**Issue by tthallos** [pipipi-pikachu/pptxtojson#22]
在 PPT 文件可以正常打开显示的前提下导入报错

https://github.com/pipipi-pikachu/pptxtojson/blob/414886c487c8b089b49d286d410be334c044d9b9/src/fontStyle.js#L32

![Screenshot 2024-06-07 at 17 00 31](https://github.com/pipipi-pikachu/pptxtojson/assets/1428407/76529dbe-77f4-4acf-97c3-1ad29ff41c4f)

![Screenshot 2024-06-07 at 17 01 13](https://github.com/pipipi-pikachu/pptxtojson/assets/1428407/2f1dc164-6784-445b-a89e-15b3e3cab1f2)

**Comment by ZhangLe1993** [comment]
这里我的做法是 try catch,
